project:
  type: website
  output-dir: docs      # use docs/ for githubpages, other cases use _site/
  render:
#    - "*.{qmd,R,py}"
    - "*.qmd"           # render all *.qmd files
    - "!site/this_dir/" # don't render a directory

    #- "!call_scripts/" # don't render a directory
  #pre-render: Rscript prerender.R #load_libraries.R
  # after rendering completes, script that removes .R files from the docs/ folder.
  #post-render: Rscript cleanup/clean_docs_dir.R

  #resources:
  #  - "webr-serviceworker.js"
  #  - "webr-worker.js"

  #resources:
  #  - figs/    # ensures that the .R files in figs/ are rendered in a website build

  # settings for previewing the website
  preview:
    port: 1671
    browser: true
    navigate: true

website:
  title: "Tennis "

  # site-url: ""
  # add optional favicon
  # favicon: "website_files/images/myfavicon.png"





  # add webpage description
  description: ""

  navbar:
    left:
      # the index file
      - text: "Tennis Homepage" # use empty string to be blank
        href: pages/Tennis_homepage.qmd



      - text: "ATP Match Overview"
        menu:
          - text: "Major Tournaments"
            href: major_page.qmd
          - text: "Court Surfaces"
            href: surface_page.qmd
          - text: "ATP Rankings"
            href: ranking_page_final.qmd
          - text: "ATP Doubles"
            href: pages/doubles.qmd

      - text: "Career Performance Trends"
        menu:
          - text: "Performance by Age"
            href: pages/age_performance.qmd
          - text: "Early Career Performance"
            href: pages/early_career.qmd

      - text: "Performance by Nationality"
        menu:
          - text: "Country Dominance"
            href: pages/leading_country_final.qmd
          - text: "American Performance"
            href: pages/american_win.qmd

  #    - text: "Conditional Probabilites"
  #      menu:
   #       - text: "--- "
  #          href: pages/leading_country_final.qmd
   #       - text: "---"
    #        href: pages/american_win.qmd


      # adding another page
 #     - text: "First Page Text"
  #      href: pages/my_first_page.qmd  # use a meaningful name


      # the about file
      - text: "Final Conclusions"
        href: about.qmd



format:
  html:
    # base case approach
    theme: cosmo   # cosmo is the default, alternatively call the .scss file, [styles/custom.scss]
    #theme: darkly  # or if you have .scss, call it [cosmo, styles/custom.scss]
    #code-link: true
    #code-fold: true
    #code-tools: true

    toc: true
    #page-layout: full
    # add option for other fonts
    include-in-header: "fonts/fontawesome.html"
    #mainfont: arial #Nunito
    #fontsize: 1.1rem # 1.2rem




# set quarto optional editor preference: source or visual
#editor: source

