project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"           # render all *.qmd files
    - "!site/this_dir/" # don't render a directory
  post-render: Rscript cleanup/clean_docs_dir.R

  preview:
    port: 1111
    browser: true
    navigate: true

website:
  title: "Website Title"

  page-footer:
    center: |
      [contact me](myemail@mydomain.com)
    left: |
      made with [Quarto](https://quarto.org)
    right: |
      [GitHub Repo](https://github.com/username/repositoryname)
    background: "black"

  description: ""

  navbar:
    left:
      - href: index.qmd
        text: Home

      - text: "First Page Text"
        href: pages/my_first_page.qmd

      - text: "Drop Tab Text"
        menu:
          - text: "Text for first option"
            href: pages/my_second_page.qmd
          - text: "Text for second option"
            href: pages/my_third_page.qmd
          - text: "Exercise Test Page"
            href: pages/team_test_page.qmd

      - text: "About Page Text"
        href: about.qmd

      - text: "The Big 3"
        menu:
          - text: "ATP Singles Ranking"
            href: pages/page1.qmd
          - text: "Major vs Non-major Wins"
            href: pages/page2.qmd
          - text: "Limitations of Visualization"
            href: pages/hw06eisenmanl.qmd
          - text: "More Visualizations"
            href: pages/hw05eisenmanl_final.qmd

    right:
      - about.qmd
      - icon: github
        href: https://github.com/username

format:
  html:
    theme: cosmo
    toc: true
    include-in-header: "fonts/fontawesome.html"
