project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
    - "about.qmd"
    - "pages/*.qmd" # render all *.qmd files in pages/
    
  preview:
    port: 1111
    browser: true
    navigate: true

website:
  title: "Tennis"
  navbar:
    left: # the right side of nav bar
      - href: index.qmd
        text: Home
      - about.qmd

      - text: "*The Big 3*"  
        menu:
        - text: "ATP Singles Ranking"
          href: pages/page1.qmd
        - text: "**Major vs Non-major Wins**"
          href: pages/page2.qmd
        - text: "**Limitations of Visualization**"
          href: pages/hw06eisenmanl.qmd
        - text: "**More Visualizations**"
          href: pages/hw05eisenmanl_final.qmd
          
    right:  # the right side of nav bar
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: [cosmo, styles/example-light.scss] # location of light theme
      dark: [cosmo, styles/example-dark.scss]   # location of dark theme
    toc: true # if you want a table of contents
